[package]
name = "ACI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ACI"
crate_type = ["cdylib"]

[dependencies]
chrono = "0.4.26"
ctor = "0.2.2"
